name: SGSI_Build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://hugeota.d.miui.com/21.5.31/miui_TUCANA_21.5.31_cb42ec9bed_11.0.zip'
      ZIP_NAME:
        description: 'ZIP_NAME'
        required: true
        default: 'miui_TUCANA_21.5.31_cb42ec9bed_11.0.zip'
      OS_TYPE:
        description: 'OS_TYPE'
        required: true
        default: 'miui'
      SGSI_TYPE:
        description: 'SGSI_TYPE(AB, A, or BOTH)'
        required: true
        default: 'AB'
      REPACK_NAME:
        description: 'REPACK_NAME'
        required: true
        default: 'SGSI.zip'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Build Time
        run: |
          echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV

      - name: Clean Environment
        run: |
          docker rmi $(docker images -q) || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* || true
          sudo apt-get update
          sudo apt-get -y autoremove --purge
          sudo apt-get clean

      - name: Install Required Tools
        run: |
          sudo apt-get install -y git wget zip unzip curl axel

      - name: Clone SGSI Tool
        run: |
          git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 11 $GITHUB_WORKSPACE/Tool-SGSI-build

      - name: Replace Custom Content
        run: |
          sudo rm -rf $GITHUB_WORKSPACE/Tool-SGSI-build/apps_clean
          sudo cp -r apps_clean $GITHUB_WORKSPACE/Tool-SGSI-build/apps_clean
          sudo chmod 777 -R $GITHUB_WORKSPACE/Tool-SGSI-build

      - name: Download ROM
        run: |
          cd $GITHUB_WORKSPACE/Tool-SGSI-build
          mkdir ./tmp
          wget -U "Mozilla/5.0" ${{ github.event.inputs.ROM_URL }} -O "./tmp/${{ github.event.inputs.ZIP_NAME }}"
          if [ ! -f "./tmp/${{ github.event.inputs.ZIP_NAME }}" ]; then
            echo "ROM download failed!" && exit 1
          fi

      - name: Configure Tool Environment
        run: |
          sudo sed -i 's/USE_MIRROR_FOR_PIP=true/USE_MIRROR_FOR_PIP=false/' $GITHUB_WORKSPACE/Tool-SGSI-build/setup.sh
          sudo bash $GITHUB_WORKSPACE/Tool-SGSI-build/setup.sh

      - name: Build AB GSI
        if: ${{ github.event.inputs.SGSI_TYPE }} == 'AB' || ${{ github.event.inputs.SGSI_TYPE }} == 'BOTH'
        run: |
          sudo bash $GITHUB_WORKSPACE/Tool-SGSI-build/make.sh AB << EOF
          ${{ github.event.inputs.ZIP_NAME }}
          y
          y
          ${{ github.event.inputs.OS_TYPE }}
          y
          EOF

      - name: Pack AB GSI
        if: ${{ github.event.inputs.SGSI_TYPE }} == 'AB' || ${{ github.event.inputs.SGSI_TYPE }} == 'BOTH'
        run: |
          cd $GITHUB_WORKSPACE/Tool-SGSI-build
          zip -r AB_${{ github.event.inputs.REPACK_NAME }} SGSI/*
          mkdir -p upload_ab
          if [ $(stat --printf="%s" AB_${{ github.event.inputs.REPACK_NAME }}) -gt 2147483647 ]; then
            tar cvzpf - AB_${{ github.event.inputs.REPACK_NAME }} | split -d -b 1024m - upload_ab/AB_
          else
            mv AB_${{ github.event.inputs.REPACK_NAME }} upload_ab/
          fi

      - name: Build A-only GSI
        if: ${{ github.event.inputs.SGSI_TYPE }} == 'A' || ${{ github.event.inputs.SGSI_TYPE }} == 'BOTH'
        run: |
          sudo bash $GITHUB_WORKSPACE/Tool-SGSI-build/make.sh A << EOF
          ${{ github.event.inputs.ZIP_NAME }}
          y
          y
          ${{ github.event.inputs.OS_TYPE }}
          y
          EOF

      - name: Pack A-only GSI
        if: ${{ github.event.inputs.SGSI_TYPE }} == 'A' || ${{ github.event.inputs.SGSI_TYPE }} == 'BOTH'
        run: |
          cd $GITHUB_WORKSPACE/Tool-SGSI-build
          zip -r AONLY_${{ github.event.inputs.REPACK_NAME }} SGSI/*
          mkdir -p upload_aonly
          if [ $(stat --printf="%s" AONLY_${{ github.event.inputs.REPACK_NAME }}) -gt 2147483647 ]; then
            tar cvzpf - AONLY_${{ github.event.inputs.REPACK_NAME }} | split -d -b 1024m - upload_aonly/AONLY_
          else
            mv AONLY_${{ github.event.inputs.REPACK_NAME }} upload_aonly/
          fi

      - name: Upload to Release
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: |
            $GITHUB_WORKSPACE/Tool-SGSI-build/upload_ab/*
            $GITHUB_WORKSPACE/Tool-SGSI-build/upload_aonly/*
          tag: "${{ github.event.inputs.REPACK_NAME }}_${{ env.BUILD_TIME }}"
          bodyFile: "$GITHUB_WORKSPACE/Tool-SGSI-build/SGSI/build_info.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
